name: GitHub Actions Build Runcat
on: 
  push:
    branch: [dev]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1        
        - run: nuget restore RunCat.sln

      - name: .Net Build
        uses: EasyDesk/action-dotnet-build@v1
        with:
          # (Optional) Additional arguments for dotnet build.
          build-args: -v normal

          # (Optional) Build configuration, defaults to 'Release'
          # If the version starts with the 'v' prefix, it will be removed to conform to the requirements of dotnet pack.
          build-configuration: Release

          # (Optional) The path of the project to build; if omitted, the whole solution is built
          path: .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls ${{ github.workspace }}\RunCat\bin\